packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  esbuild: true
  spawn-sync: false

catalog:
  typescript: ^5.9.0
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  vitest: ^4.0.0
