import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { simulateColor } from '../src/simulate';
import type { CvdType, RGBTuple } from '../src/types';

interface GoldenFile {
  grid: number;
  combos: { type: CvdType; severity: number; expected: string }[];
}

// Generated by tools/gen-golden.py — see its header for the regeneration command.
const golden: GoldenFile = JSON.parse(
  readFileSync(new URL('./golden/daltonlens-grid.json', import.meta.url), 'utf8'),
);

const STEPS = golden.grid;
const values = Array.from({ length: STEPS }, (_, i) => Math.round((i * 255) / 16));
const grid: RGBTuple[] = [];
for (const r of values) {
  for (const g of values) {
    for (const b of values) {
      grid.push([r, g, b]);
    }
  }
}

describe('simulateColor matches DaltonLens-Python over the 17³ grid', () => {
  it.each(golden.combos.map((c) => [c.type, c.severity, c.expected] as const))(
    '%s severity %d: max per-channel |delta| <= 1',
    (type, severity, expected) => {
      const want = Buffer.from(expected, 'base64');
      expect(want.length).toBe(grid.length * 3);
      let maxDelta = 0;
      for (let i = 0; i < grid.length; i++) {
        const got = simulateColor(grid[i], type, severity);
        for (let k = 0; k < 3; k++) {
          maxDelta = Math.max(maxDelta, Math.abs(got[k] - want[i * 3 + k]));
        }
      }
      expect(
        maxDelta,
        `${type} severity ${severity}: max per-channel |delta| was ${maxDelta}`,
      ).toBeLessThanOrEqual(1);
    },
  );
});
